---
title: "Figure 3 Mean Difference"
author: "Eric Bridgeford"
date: "January 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Parallelize Stuff
#=========================#
library(parallel)

no_cores = detectCores() - 1

cl = makeCluster(no_cores)

# Setup Sims
#==========================#
require(lol)
n=100
niter <- 50  # number of iterations per simulation
rlen <- 30
# the simulations to call themselves
sims <- list(lol.sims.mean_diff)
maxr <- c(30)
ds <- c(100)
# additional arguments for each simulation scenario
opt_args <- list(list(md=1))
sim_names = c("Mean Difference")

simulations <- list()
counter <- 1

for (i in 1:length(sims)) {
  for (j in 1:niter) {
    simulations[[counter]] <- list(sim_func=sims[[i]], args=c(list(n, ds[i]), opt_args[[i]]),
                                   rmax=maxr[i], sim=sim_names[i], iter=j)
    counter <- counter + 1
  }
}

# Setup Algorithms
#=========================#
algs <- list(lol.project.lrcca, lol.project.lol)
alg_name <- c("LR-CCA", "LOL")

clusterExport(cl, "algs"); clusterExport(cl, "alg_name")
clusterExport(cl, "simulations"); clusterExport(cl, "rlen")
results <- parLapply(cl, simulations, function(sim) {
  require(lol)
  sim_dat <- do.call(sim$sim_func, sim$args)
  X <- sim_dat$X; Y <- sim_dat$Y
  results <- data.frame(sim=c(), iter=c(), alg=c(), r=c(), lhat=c())
  for (i in 1:length(algs)) {
    rs <- round(seq(from=1, to=sim$rmax, length.out=rlen))
    for (r in rs) {
      tryCatch({
        xv_res <- lol.xval.eval(X, Y, r, algs[[i]])
        lhat <- xv_res$Lhat
      }, error=function(e) lhat <- NaN)
      results <- rbind(results, data.frame(sim=sim$sim, iter=sim$iter, alg=alg_name[i], r=r, lhat=lhat))
    }
  }
  return(results)
})


# Aggregate and save
#=================================#
require(data.table)
results <- do.call(rbind, results)
results <- data.table(results)
# aggregate over the iterations, retaining the other factors
results.means <- aggregate(lhat ~ sim + alg + r + lhat, data = results, FUN = mean)
```

```{r}
cov_plots <- list()
mean_plots <- list()
counter <- 1

for (i in 1:length(sims)) {
  simn <- do.call(sims[[i]], c(list(n, ds[i]), opt_args[[i]]))
  cov_plots[[counter]] <- sim_cov_plot(simn$Sigmas, title=sim_names[i])
  mean_plots[[counter]] <- sim_mean_plot(simn$mus, title=sim_names[i], ndim=ndim[i])
  counter <- counter + 1
}

sim_plots <- list()
counter <- 1
for (sim in unique(results.means$sim)) {
  data_sub <- results.means[results.means$sim == sim,]
  sim_plots[[counter]] <- plot_sim_lhats(data_sub, ylab=sim)
  counter <- counter + 1
}
```

```{r}

```
