---
title: "Low-Rank Canonical Correlation Analysis (LR-CCA)"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE}
require(fselect)
require(ggplot2)
require(latex2exp)
```
# LRCCA Example

We simulate data with n=200, d=30 and visualize the first 2 dimensions:
```{r}
testdat <- fs.sims.rtrunk(200, 30)
X <- testdat$X
Y <- testdat$Y

data <- data.frame(x1=X[,1], x2=X[,2], y=Y)
data$y <- factor(data$y)
ggplot(data, aes(x=x1, y=x2, color=y)) +
  geom_point() +
  xlab(TeX("$x_1$")) +
  ylab(TeX("$x_2$")) +
  ggtitle("Simulated Data")
```

Projecting with LRCCA to 3 dimensions and visualizing the first 2:

```{r}
result <- fs.project.lrcca(X, Y, 3)

data <- data.frame(x1=result$Xr[,1], x2=result$Xr[,2], y=Y)
data$y <- factor(data$y)
ggplot(data, aes(x=x1, y=x2, color=y)) +
  geom_point() +
  xlab(TeX("$x_1$")) +
  ylab(TeX("$x_2$")) +
  ggtitle("Projected Data using LRCCA")
```

Projecting with LDA to $K-1=1$ dimensions:

```{r}
result <- fs.classify.lda(result$Xr, Y, result$Xr, Y.test=Y)

data <- data.frame(x1=result$Xr.train[,1], y=Y)
data$y <- factor(data$y)
ggplot(data, aes(x=x1, fill=y)) +
  geom_density(adjust=1.5, alpha=0.6) +
  xlab(TeX("$x_1$")) +
  ylab(TeX("Density")) +
  ggtitle(TeX(sprintf("$LRCCA \\rightarrow LDA$, $\\hat{L} = %.2f$", result$Lhat)))
```
